# Generated by Django 4.1.2 on 2022-10-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_profile_user_alter_profile_pix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
